packages:
  - 'apps/admin'
  - 'apps/api'
  - 'apps/evans'
  - 'apps/native'
  - 'apps/cover-web-app'
  - 'apps/fell'
  - 'apps/storybook-web'
  - 'apps/cli'
  - 'apps/jones'
  - 'apps/styleguide'
  - 'libs-ts/*'
  - 'libs-swift/*'
