_default:
  @just --choose

dev-en: write-cover-css
  @NEXT_PUBLIC_LANG=en pnpm dev --port 7222

dev-es: write-cover-css
  @NEXT_PUBLIC_LANG=es pnpm dev --port 7333

storybook:
  @cd ../../ && pnpm --filter storybook storybook

prisma-generate:
  @test -e ../../.env || cp ../../.env.example ../../.env
  @cp ../../.env ./.env
  @pnpm prisma generate
  @rm ./.env

[private]
write-cover-css:
  @pnpm ts-node ./lib/cover-static-css.ts
