_default:
  @just --choose

install-ios:
  @pnpm react-native run-ios

install-ios-release:
  @pnpm react-native run-ios --configuration Release

install-android:
  @pnpm react-native run-android

install-android-release:
  @pnpm react-native run-android --mode release

install: install-ios install-android

start:
  @pnpm react-native start

start-reset-cache:
  @pnpm react-native start --reset-cache

xcode:
  @open ios/FriendsLibrary.xcworkspace

pod-install:
  @cd ios && bundle exec pod install

set-env lang:
  @pnpm ts-node ./env/set-env.ts {{lang}}

set-env-en:
  @just set-env en

set-env-es:
  @just set-env es

clean:
  @cd android && ./gradlew clean
