name: should-republish-evans
inputs:
  flp_api_endpoint:
    required: true
  flp_api_token:
    required: true
outputs:
  should_republish:
    description: "'true' if evans needs to be republished"
  build_data_cloud_filepath:
    description: cloud filepath of build data for deploy error handling
runs:
  using: node16
  main: ./bundled/index.js
