extension ArtifactProductionVersion: ApiModel {}
extension Audio: ApiModel {}
extension AudioPart: ApiModel {}
extension Document: ApiModel {}
extension DocumentTag: ApiModel {}
extension Download: ApiModel {}
extension Edition: ApiModel {}
extension EditionChapter: ApiModel {}
extension EditionImpression: ApiModel {}
extension FreeOrderRequest: ApiModel {}
extension Friend: ApiModel {}
extension FriendQuote: ApiModel {}
extension FriendResidence: ApiModel {}
extension FriendResidenceDuration: ApiModel {}
extension Isbn: ApiModel {}
extension NativeAppError: ApiModel {}
extension NPQuote: ApiModel {}
extension NPSentQuote: ApiModel {}
extension NPSubscriber: ApiModel {}
extension Order: ApiModel {}
extension OrderItem: ApiModel {}
extension RelatedDocument: ApiModel {}
extension Token: ApiModel {}
extension TokenScope: ApiModel {}
