_default:
  @just --choose

run-ios:
  @pnpm react-native run-ios

run-android:
  @pnpm react-native run-android

start:
  @pnpm react-native start

start-reset-cache:
  @pnpm react-native start --reset-cache

xcode:
  @open ios/xnative.xcworkspace

pod-install:
  @cd ios && bundle exec pod install

