_default:
  @just --choose

install-ios:
  @pnpm react-native run-ios

install-android:
  @pnpm react-native run-android

install: install-ios install-android

start:
  @pnpm react-native start

start-reset-cache:
  @pnpm react-native start --reset-cache

xcode:
  @open ios/xnative.xcworkspace

pod-install:
  @cd ios && bundle exec pod install

