[dev]
  command = "pnpm run dev"

[build]
  command = "mv ../../libs-ts/adoc-lint/src/character-name{.browser,}.ts && pnpm run build"
  publish = "dist/"
  functions = "src/functions"

[build.environment]
  NODE_VERSION = "18.13.0"
