name: ci

on:
  push:

jobs:
  test-typescript:
    name: test-typescript
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup ci
        uses: ./.github/actions/setup-ci
      - name: test typescript
        run: just test-typescript

  lint-typescript:
    name: lint-typescript
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup ci
        uses: ./.github/actions/setup-ci
      # - name: format
      #   run: just format-check
      - name: lint
        run: just lint

  admin:
    name: admin
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup ci
        uses: ./.github/actions/setup-ci
      - name: build-admin
        run: cd apps/admin && pnpm build
